kind: ReplicationController
apiVersion: v1
metadata:
  name: flink-worker-controller
  namespace: flink-cluster
spec:
  replicas: 3
  selector:
    component: flink-worker
  template:
    metadata:
      labels:
        component: flink-worker
    spec:
      containers:
        - name: flink-worker
          image: melentye/flink
          command: ["/opt/flink/bin/start-worker.sh"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
          resources:
            requests:
              cpu: 100m