kind: ReplicationController
apiVersion: v1
metadata:
  name: taskmanager-controller
  namespace: flink
spec:
  replicas: 3
  selector:
    component: taskmanager
  template:
    metadata:
      labels:
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: melentye/flink:1.1.3-custom-akka3
          args: ["taskmanager", "jobmanager.flink.svc.cluster.local"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
          resources:
            requests:
              cpu: 100m
